### ISSUE TITLE
Asking NEI for Tinker's Construct recipies crashes the client

### ISSUE THREAD

**Issue by keturn** [breakinblocks/nutsandbolts#136]
In Nuts and Bolts v3.5, when I click on the Recipes icon on a Tinker's Construct material, the client crashes. This seems to be consistently reproducible.

```
-- Head --
Stacktrace:
	at tconstruct.plugins.nei.RecipeHandlerToolMaterials.loadCraftingRecipes(RecipeHandlerToolMaterials.java:186)
	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:466)
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)

-- Affected screen --
Details:
	Screen name: codechicken.nei.recipe.GuiUsageRecipe
```

More of the report at https://gist.github.com/3ee17d48217675e950a4435bbf42dec9

**Comment by keturn** [comment]
This is the button to not click: [Screenshot](http://i.imgur.com/1IF20HR.jpg)

**Comment by keturn** [comment]
Also reproducible in single-player.

**Comment by Saereth** [comment]
fixed in new version

**Comment by keturn** [comment]
Can still reproduce :slightly_frowning_face: https://gist.github.com/2510ef0e6f993c6b67bdb0a31dc896ca
